### ISSUE TITLE
.external-link bauble is hidden but spacing remains

### ISSUE THREAD

**Issue by kees-** [Bluemoondragon07/chime-theme#3]
Obsidian v1.1.9
Chime theme 1.1.2
MacOS 12

Setting

```css
.external-link {
  image-decoration: none;
}
```

removes the image appending links but the space it occupies is not addressed. `padding-right: unset` fixes this if that's your intent!

<img width="788" alt="Image 2023-02-05 at 3 56 54 PM" src="https://user-images.githubusercontent.com/6820950/216853445-bf64bba7-c056-48c8-b97e-7b16f231012b.png">
